trigger:
  batch: true
  branches:
    include:
      - '*'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.9.1'
  inputs:
    versionSpec: '4.9.1'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'src/**/*.UnitTests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Nuget Package main project'
  inputs:
    command: 'pack'
    packagesToPack: 'src/MockTheWeb/MockTheWeb.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: 'Nuget Package Newtonsoft project'
  inputs:
    command: 'pack'
    packagesToPack: 'src/MockTheWeb.NewtonsoftJson/MockTheWeb.NewtonsoftJson.csproj'
    nobuild: true
    versioningScheme: 'off'

- task: CopyFiles@2
  displayName: 'Copy nupkg'
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
