trigger:
- master

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/**/*.UnitTests.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/MockTheWeb/MockTheWeb.csproj'
    versioningScheme: 'off'

- task: CopyFiles@2
  inputs:
    SourceFolder: '**'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'